### ISSUE TITLE
Some code blocks do not render correctly.

### ISSUE THREAD

**Issue by psyrendust** [assemble/assemble-boilerplate-bootstrap#10]
There seems to be a consistent issue around the rendering of some code blocks.
##### Some code blocks are not colored correctly

---

http://assemble.github.io/boilerplate-bootstrap/javascript.html#scrollspy-usage 
![image](https://f.cloud.github.com/assets/928502/1098146/36b798fc-171c-11e3-9f26-4086b0625e61.png)

http://getbootstrap.com/javascript/#scrollspy-usage
![image](https://f.cloud.github.com/assets/928502/1098167/71aeb6ca-171c-11e3-88a7-8eb6bf6f75fa.png)
##### Other code blocks are just plain wacky

---

http://assemble.github.io/boilerplate-bootstrap/javascript.html#scrollspy-usage
![image](https://f.cloud.github.com/assets/928502/1098196/c08283d0-171c-11e3-95a7-a498130cc267.png)

http://getbootstrap.com/javascript/#scrollspy-usage
![image](https://f.cloud.github.com/assets/928502/1098206/de70ca82-171c-11e3-9c31-48f9f399f83e.png)

**Comment by jonschlinkert** [comment]
I'm looking into this now, thanks

**Comment by jonschlinkert** [comment]
Okay, here is what is going on, the first example "via javascript" was a simple matter of the Bootstrap versions being different, so I rebuilt with the latest and pushed back up. 

However, as for the second example:

![image](https://f.cloud.github.com/assets/383994/1101775/420e4c14-17df-11e3-9708-21e14919dea5.png)

Here is the code generated by Assemble, which then compiles into HTML:

![image](https://f.cloud.github.com/assets/383994/1101784/642a44e2-17df-11e3-9a30-ce83e4b54e5d.png)

As you can see, the code is quite clean, and the conversion should happen cleanly as well. My guess is that either marked.js is incorrectly formatting the JavaScript or highlight.js is incorrectly applying styles. I haven't been able to dig deeper yet, I just wanted to post my thoughts in case you have any ideas (I might not able to come back to this today)

**Comment by psyrendust** [comment]
I've been wondering if it's an issue with marked.js. I tried to use a different highlighter (node-pygementize-bundled) as stated in their example but they are doing something wonky where they always wrap the code blocks the same way no matter what highlighter you use. The bit of code I'm referring to is here: https://github.com/chjj/marked/blob/master/lib/marked.js#L856-L879

``` javascript
    case 'code': {
      if (this.options.highlight) {
        var code = this.options.highlight(this.token.text, this.token.lang);
        if (code != null && code !== this.token.text) {
          this.token.escaped = true;
          this.token.text = code;
        }
      }

      if (!this.token.escaped) {
        this.token.text = escape(this.token.text, true);
      }

      return '<pre><code'
        + (this.token.lang
        ? ' class="'
        + this.options.langPrefix
        + this.token.lang
        + '"'
        : '')
        + '>'
        + this.token.text
        + '</code></pre>\n';
    }
```

**Comment by jonschlinkert** [comment]
Closing since it has been a while. also, technically there isn't any reason to keep Bootstrap's documentation in tact once it's built with this. however, once you get your own code examples up and running, if you have the same issues I'd recommend creating an issue either on the assemble repo or wherever you think is appropriate based on the most likely cause
