### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by toby1kenobi** [assemble/assemble-boilerplate-bootstrap#15]
Of the three methods in [Quickstart/First](https://github.com/assemble/boilerplate-bootstrap#quickstart) I've only been able to get the middle to work. Downloading the zip and running the initial `npm i`  is fine, but the `bower install` possibly ceases at

```
bower js-prettify#~1.4.0     ENOTFOUND Package js-prettify not found
```

After that there's no `vendor/bootstrap` to cd into. Running `bower install boilerplate-bootstrap`` doesn't work, bower can't find anything with that name.

Apologies if some or all of the above is down to my ignorance, it's seem like it should be straight forward though.

Toby

**Comment by ErnstHaagsman** [comment]
I'm having the same issue here.

**Comment by jonschlinkert** [comment]
thanks for the heads up, js-prettify needs to be registered with bower.

**Comment by jonschlinkert** [comment]
I think this should be fixed, but it would be great to have verification that you're also able to install correctly.

**Comment by toby1kenobi** [comment]
Yep, the install seems to run ok now - thanks!

**Comment by vnys** [comment]
The bower install method fails again I’m afraid. Running <code>bower install boilerplate-bootstrap</code> returns <code>ENOTFOUND Package boilerplate-bootstrap not found</code>.

**Comment by hariadi** [comment]
Just run `bower install`

**Comment by jonschlinkert** [comment]
turns out @batfink was right, this wasn't even registered on bower! doh! I thought it was! thanks, should be fixed now!
