### ISSUE TITLE
Grunt build weirdness?

### ISSUE THREAD

**Issue by toby1kenobi** [assemble/assemble-boilerplate-bootstrap#16]
This might be entirely intentional, I can't quite tell from your description?! 

Having installed boilerplate-bootstrap I'm seeing some counter-intuitive behaviour when I build it - any changes I make in `src/*.hbs` are immediately lost/overwritten? It seems that I have to make changes in `vendor/bootstrap/*.html` and these are then moved into the *.hbs files, is that correct?

**Comment by jonschlinkert** [comment]
Yeah, this is intentional until you change the config in the gruntfile to do otherwise. You only really need to build "original" Bootstrap once. After that you can customize it however you want.
