### ISSUE TITLE
npm package mispelled, publish fix for issue #5 to npm

### ISSUE THREAD

**Issue by psyrendust** [assemble/assemble-boilerplate-bootstrap#9]
Publish fix for issue #5 to npm. On npm the package is incorrectly named.

Currently: 

```
https://npmjs.org/package/assemble-bootstap
```

Should be:

```
https://npmjs.org/package/assemble-bootstrap
```

The package.json is still showing an incorrect name.

**Comment by hariadi** [comment]
Already [here](https://npmjs.org/package/assemble-bootstrap)

**Comment by jonschlinkert** [comment]
it doesn't look like it was fixed in all of the paths in the package.json. @psyrendust thank you, I went ahead and renamed the package to it's consistent.
